# Generated by Django 3.2.7 on 2021-09-18 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_king', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('death', models.PositiveSmallIntegerField(default=0)),
                ('capture', models.PositiveSmallIntegerField(default=0)),
                ('attacker_size', models.PositiveSmallIntegerField(default=0)),
                ('defender_size', models.PositiveSmallIntegerField(default=0)),
                ('is_summer', models.BooleanField(default=False)),
                ('note', models.TextField(default=str, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('attacker_king', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attacker_king_battles', to='wars.warrior')),
                ('attackers', models.ManyToManyField(related_name='attackers_battles', to='wars.Warrior')),
                ('defender_king', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defender_king_battles', to='wars.warrior')),
                ('defenders', models.ManyToManyField(related_name='defenders_battles', to='wars.Warrior')),
            ],
        ),
    ]
