# Generated by Django 3.2.7 on 2021-09-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_commanders',
            field=models.ManyToManyField(related_name='attacker_commanders_battles', to='wars.Warrior'),
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_number',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_commanders',
            field=models.ManyToManyField(related_name='defender_commanders_battles', to='wars.Warrior'),
        ),
        migrations.AddField(
            model_name='battle',
            name='is_attacker_win',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='battle',
            name='attacker_size',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='capture',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='death',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='defender_size',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='is_summer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=80, null=True)),
                ('region',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_locations',
                                   to='wars.region')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='battle_type_battles', to='wars.battletype'),
        ),
        migrations.AddField(
            model_name='battle',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='location_battles', to='wars.location'),
        ),
    ]
