# Generated by Django 3.2.7 on 2021-09-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0003_alter_battle_battle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='is_attacker_win',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
