# Generated by Django 3.2.7 on 2021-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0004_auto_20210921_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battletype',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(db_index=True, max_length=70, unique=True),
        ),
    ]
